### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by bam80** [joereynolds/joereynolds.github.io#11]
Hi Joe, thank you for the blog, I would like to subscribe over RSS, if possible :)

**Comment by joereynolds** [comment]
Hey Bam80,

Glad you like my stuff! I do have an RSS feed, the URL is
https://joereynoldsaudio.com/feed

Thanks!

**Comment by bam80** [comment]
Indeed. How about making the link accessible from homepage? :)

**Comment by joereynolds** [comment]
Nice suggestion, I'll start on it soon

**Comment by joereynolds** [comment]
Here y'go

https://github.com/joereynolds/joereynolds.github.io/commit/163c34ef7cf851bfb96ef3a37ea95393824995c7

:)

**Comment by bam80** [comment]
FYI, now it discovered by Feedly ;)
